### ISSUE TITLE
Setup failed for dependencies

### ISSUE THREAD

**Issue by krisxnlx** [milanvo/hass-components#2]
Hi mate, 

If this works it would be great!
First error; 

No module named 'smbus'

So i installed this, but then;

2019-02-08 11:58:59 ERROR (MainThread) [homeassistant.setup] Error during setup of component ups_pico
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/setup.py", line 145, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/ups_pico.py", line 47, in async_setup
    UPS_DATA = UpsPico()
  File "/config/custom_components/ups_pico.py", line 132, in __init__
    self.i2c = smbus2.SMBus(1)
  File "/usr/local/lib/python3.6/site-packages/smbus2/smbus2.py", line 253, in __init__
    self.open(bus)
  File "/usr/local/lib/python3.6/site-packages/smbus2/smbus2.py", line 265, in open
    self.fd = os.open("/dev/i2c-{}".format(bus), os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/i2c-1'
2019-02-08 11:58:59 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of switch.ups_pico. Setup failed for dependencies: ups_pico
2019-02-08 11:58:59 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform switch.ups_pico: Could not set up all dependencies.

I cant get it to work :(

**Comment by krisxnlx** [comment]
I have had to make some adjustments to the HomeAssistant docker container to get this working. I have been working for ages to add a second RFLink and it has finally succeeded! Thank you very much!!!

**Comment by krisxnlx** [comment]
Unfortunately there is another error now :( 
I cheered too early xD

Error;
(MainThread) [custom_components.ups_pico] Except class UPS PIco _try_get_data(): [Errno 6] No such device or address

**Comment by milanvo** [comment]
Hi,

so you try to make it work on RPI with HassIO (HassOS) hypervisor ? Unfortunately I have no experience with this setup.

Errors looks like component cannot comminicate via I2C bus with UPS Pico 

UPS Pico works in general ? Status led “UPS” blinking and battery charging ?
(picofssd sending pulse train / heartbeat to UPS board)
Do you enabled I2C in HassOS ? https://github.com/home-assistant/hassos/blob/dev/Documentation/boards/raspberrypi.md

I am not sure how specific environment is with HassIO, general setup and check of I2C on RPI with Raspbian: 
https://learn.adafruit.com/adafruits-raspberry-pi-lesson-4-gpio-setup/configuring-i2c

**Comment by krisxnlx** [comment]
Hey, 

My Homeassistant installation is running on a Ubuntu server on a small form factor PC.
This PC does have a I2C bus so I thought it should work.

It makes more sense to me know :) i will try to edit UPS Pico so i will work without the specific I2C bus.
Ill come back at this.

Thanks and greetz 
Kris

**Comment by krisxnlx** [comment]
Hi, 

UPS Pico seems to run for now.
RFLink2 can only receive data but not send it , is this correct?

Greetz,
Kris

**Comment by milanvo** [comment]
If I understand correctly, you have UPS PIco (from Pimodules 
https://www.modmypi.com/raspberry-pi/power-1051/ups-boards-1051) connected to  different HW platform than Raspberry Pi ? Interesting...

With Rflink2 custom component, I am not tested to send data. It is original HA component with just DOMAIN changed, using same device and entity data structure. So there is probability it can work 😉 

My use case is - primary RFLink for Somfy RTS control, secondary (rflink2) for receiving data from cheap 433MHz temp sensors.

**Comment by krisxnlx** [comment]
Hi Milanvo,

I was more interested in the RF link that both send and receive. I will unfortunately have to search further. Thanks for your help.

Greetz
